### ISSUE TITLE
Feature Request: Add Tags for Supervised/Unsupervised Learning in Time-Series Segmentation

### ISSUE THREAD

**Issue by blacksnail789521** [lzz19980125/awesome-time-series-segmentation-papers#1]
I have been utilizing the curated lists of papers on time-series segmentation available in this repository and found them extremely valuable. However, it would be more user-friendly if the papers could be tagged based on whether they address supervised or unsupervised learning approaches. For example, the method presented in PrecTime is based on supervised learning, similar to the SAM framework by Meta in the field of computer vision.

Adding tags such as "Supervised" or "Unsupervised" to each paper would make it easier for researchers and practitioners to quickly find relevant studies according to their specific needs in time-series analysis.

Thank you for considering this suggestion. Implementing it could enhance usability and help users efficiently navigate through the diverse methodologies.

**Comment by lzz19980125** [comment]
Thank you for your suggestion. In fact, due to the lack of large-scale public datasets with ground truth (except in the field of motion capture), most research in the area of time series segmentation is unsupervised, especially studies not based on deep learning. Currently, 95% of the research work included in this repository is unsupervised. 

I will add this explanation to the README.
